In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("iris.csv")

In [3]:
df

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [8]:
df.groupby('variety')[['sepal.length','sepal.width','petal.length','petal.width']].agg(
    ['mean','median','min','max','std']
)

           sepal.length                            sepal.width              \
                   mean median  min  max       std        mean median  min
variety
Setosa            5.006    5.0  4.3  5.8  0.352490       3.428    3.4  2.3
Versicolor        5.936    5.9  4.9  7.0  0.516171       2.770    2.8  2.0
Virginica         6.588    6.5  4.9  7.9  0.635880       2.974    3.0  2.2

                          petal.length                            petal.width  \
            max       std         mean median  min  max       std        mean
variety
Setosa      4.4  0.379064        1.462   1.50  1.0  1.9  0.173664       0.246
Versicolor  3.4  0.313798        4.260   4.35  3.0  5.1  0.469911       1.326
Virginica   3.8  0.322497        5.552   5.55  4.5  6.9  0.551895       2.026


           median  min  max       std
variety
Setosa        0.2  0.1  0.6  0.105386
Versicolor    1.3  1.0  1.8  0.197753
Virginica     2.0  1.4  2.5  0.274650

In [12]:
df.groupby('variety')[['sepal.length','sepal.width','petal.length','petal.width']].apply(lambda x: x.values.tolist())

variety
Setosa        [[5.1, 3.5, 1.4, 0.2], [4.9, 3.0, 1.4, 0.2], [...
Versicolor    [[7.0, 3.2, 4.7, 1.4], [6.4, 3.2, 4.5, 1.5], [...
Virginica     [[6.3, 3.3, 6.0, 2.5], [5.8, 2.7, 5.1, 1.9], [...
dtype: object

In [17]:
df.groupby('variety')['sepal.length'].apply(list)

variety
Setosa        [5.1, 4.9, 4.7, 4.6, 5.0, 5.4, 4.6, 5.0, 4.4, ...
Versicolor    [7.0, 6.4, 6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, ...
Virginica     [6.3, 5.8, 7.1, 6.3, 6.5, 7.6, 4.9, 7.3, 6.7, ...
Name: sepal.length, dtype: object

In [18]:
df.groupby('variety').describe()

           sepal.length                                              \
                  count   mean       std  min    25%  50%  75%  max
variety
Setosa             50.0  5.006  0.352490  4.3  4.800  5.0  5.2  5.8
Versicolor         50.0  5.936  0.516171  4.9  5.600  5.9  6.3  7.0
Virginica          50.0  6.588  0.635880  4.9  6.225  6.5  6.9  7.9

           sepal.width         ... petal.length      petal.width         \
                 count   mean  ...          75%  max       count   mean
variety                        ...
Setosa            50.0  3.428  ...        1.575  1.9        50.0  0.246
Versicolor        50.0  2.770  ...        4.600  5.1        50.0  1.326
Virginica         50.0  2.974  ...        5.875  6.9        50.0  2.026


                 std  min  25%  50%  75%  max
variety
Setosa      0.105386  0.1  0.2  0.2  0.3  0.6
Versicolor  0.197753  1.0  1.2  1.3  1.5  1.8
Virginica   0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 32 columns]

In [22]:
#OR
df[df['variety']=='Setosa'].describe()

       sepal.length  sepal.width  petal.length  petal.width
count      50.00000    50.000000     50.000000    50.000000
mean        5.00600     3.428000      1.462000     0.246000
std         0.35249     0.379064      0.173664     0.105386
min         4.30000     2.300000      1.000000     0.100000
25%         4.80000     3.200000      1.400000     0.200000
50%         5.00000     3.400000      1.500000     0.200000
75%         5.20000     3.675000      1.575000     0.300000
max         5.80000     4.400000      1.900000     0.600000